[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"]
eth-rpc-url = "https://eth-goerli.g.alchemy.com/v2/ytUU1rBxHZbw7q2aTr1Csv1KFgaWmpoy"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
